name: Auto Merge Oldest Pull Request

on:
    schedule:
        # Run every hour
        - cron: "0 */4 * * *"
    workflow_dispatch:

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Merge oldest mergeable pull request
              run: |
                  # Get the oldest mergeable PR (sorted by creation date, ascending)
                  PR_NUMBER=$(gh pr list --state open --json number,createdAt,mergeable --jq 'sort_by(.createdAt) | .[] | select(.mergeable == "MERGEABLE") | .number' | head -n 1)

                  if [ -z "$PR_NUMBER" ]; then
                  echo "No mergeable PRs found."
                  exit 0
                  fi

                  echo "Oldest mergeable PR $PR_NUMBER"

                  # Check mergeable before merining to reduce chance of racy merge
                  MERGEABLE=$(gh pr view "$PR_NUMBER" --json mergeable --jq '.mergeable')
                  if [ "$MERGEABLE" != "MERGEABLE" ]; then
                    echo "PR #$PR_NUMBER is no longer mergeable (status: $MERGEABLE)"
                    exit 1
                  fi

                  echo "Merging PR $PR_NUMBER"
                  if gh pr merge "$PR_NUMBER" --merge --delete-branch; then
                      echo "PR $PR_NUMBER meged successfully"
                  else
                      echo "Failed to merge PR $PR_NUMBER"
                      exit 1
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
